import argparse,json,hashlib,urllib.request,copy,base64
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PublicKey
def get(u):return json.load(urllib.request.urlopen(u))
def post(u,o):
 d=json.dumps(o).encode();r=urllib.request.Request(u,data=d,headers={'content-type':'application/json'});return json.load(urllib.request.urlopen(r))
def verify_eval(x):
 r=x.get('independent_evaluator');
 if not r or r.get('result')!='PASS' or r.get('organization_id')==x['target']['vendor_organization_id']:return False
 p=(f"RGI-EVALUATOR-1.0\nbundle_id={x['bundle_id']}\ntarget_id={x['target']['target_id']}\nstate_id={x['state']['state_id']}\nprofile_sha256={x['profile']['sha256']}\nresult=TIER_3_CERTIFIED\ntier=3\n").encode()
 try:Ed25519PublicKey.from_public_bytes(base64.b64decode(r['public_key_base64'])).verify(base64.b64decode(r['signature_base64']),p);return base64.b64decode(r['signed_payload_base64'])==p
 except:return False
def derive(x,p,ph):
 s=x['state'];g={};c=s['producer']['conformance'];g['protocol']=s['spec_version']=='0.1.0' and s['status']=='AVAILABLE' and 'BS-RGU-PRODUCER-0.1' in c and 'RGI-RGU-1.0' in c and abs(s['brodzinski']['number']['value']-sum(s['brodzinski']['number']['components'].values()))<1e-12;sc=p['scope'];g['scope']=x['profile']['sha256']==ph and s['subject']['type']==sc['subject_type'] and s['subject']['scope']==sc['subject_scope'] and s['resources']['primary']['id']==sc['primary_resource'] and s['chart']['id']==sc['chart_id'] and s['measurement']['method_id']==sc['measurement_method_id'] and s['measurement']['profile_id']==sc['measurement_profile_id']
 if not g['protocol'] or not g['scope']:return {'tier':0,'result':'NONCONFORMING','gates':g}
 a=x['assurance'];q=a['native_resource_quantum'];ch=a['measurement_channel'];cp=p['measurement']['channel'];nq=p['measurement']['native_quantum'];g['assurance']=a['native_preflight']['status']=='PASS' and a['adapter_fidelity']['status']=='PASS' and q['status']=='PASS' and q['unit']==nq['unit'] and q['quantum']<=nq['max_quantum'] and q['nonzero_probes']>=nq['min_nonzero_probes'] and q['distinct_states']>=nq['min_distinct_states'] and ch['classification']=='CHANNEL_CERTIFIED' and ch['construction']['fpr']<=cp['fpr_max'] and ch['construction']['tpr']>=cp['tpr_min'] and ch['verification']['fpr']<=cp['fpr_max'] and ch['verification']['tpr']>=cp['tpr_min']
 if not g['assurance']:return {'tier':1,'result':'TIER_1_PROTOCOL','gates':g}
 z=x['blind'];g['final']=z['prediction_commitment']['status']=='PASS' and z['prediction_commitment']['committed_before_release'] and z['outcome_release']['status']=='PASS' and z['outcome_release']['released_after_prediction'] and z['benchmark_result']['status']=='PASS' and z['prediction_commitment']['predicted_class']==z['benchmark_result']['observed_class'] and x['reproducibility']['status']=='PASS' and x['canonical_finality']['status']=='FINAL' and verify_eval(x)
 return {'tier':3,'result':'TIER_3_CERTIFIED','gates':g} if g['final'] else {'tier':2,'result':'TIER_2_ASSURED','gates':g}
def main():
 a=argparse.ArgumentParser();a.add_argument('--base',required=True);a.add_argument('--subject',required=True);a.add_argument('--profile',required=True);a.add_argument('--final');a.add_argument('--out',required=True);z=a.parse_args();pb=open(z.profile,'rb').read();p=json.loads(pb);ph=hashlib.sha256(pb).hexdigest();checks=[];caps=get(z.base+'/rgi/v1/capabilities');checks += [('rgi-version',caps['rgi_version']=='1.0.0'),('bs-compat',caps['bs_core_compatibility']=='BS-CORE-1.0-COMPAT'),('profile-hash',caps['benchmark_profiles'][0]['sha256']==ph)];rp=get(z.base+f"/rgi/v1/benchmark-profiles/{p['profile_id']}/{p['version']}");checks.append(('profile-exact',rp==p));s=get(z.base+'/rgi/v1/states/'+z.subject);checks += [('theta-components',abs(s['brodzinski']['number']['value']-sum(s['brodzinski']['number']['components'].values()))<1e-12),('local-state',s['subject']['id']==z.subject),('no-global-theta','global_theta' not in json.dumps(s))];c=get(z.base+'/rgi/v1/certification-candidates/'+z.subject);d=derive(c,p,ph);checks += [('candidate-tier2',d['result']=='TIER_2_ASSURED'),('self-eval-tier2',post(z.base+'/rgi/v1/certification/evaluate',c)['result']=='TIER_2_ASSURED')]
 final_result=None
 if z.final:
  f=json.load(open(z.final));final_result=derive(f,p,ph);checks += [('evaluator-signature',verify_eval(f)),('final-tier3',final_result['result']=='TIER_3_CERTIFIED'),('self-eval-tier3',post(z.base+'/rgi/v1/certification/evaluate',f)['result']=='TIER_3_CERTIFIED')];bad=copy.deepcopy(f);bad['profile']['sha256']='0'*64;checks.append(('negative-profile',derive(bad,p,ph)['result']=='NONCONFORMING'));bad=copy.deepcopy(f);bad['assurance']['native_preflight']['status']='FAIL';checks.append(('negative-preflight',derive(bad,p,ph)['result']=='TIER_1_PROTOCOL'));bad=copy.deepcopy(f);bad.pop('independent_evaluator');checks.append(('negative-evaluator',derive(bad,p,ph)['result']=='TIER_2_ASSURED'));bad=copy.deepcopy(f);bad['blind']['benchmark_result']['observed_class']='MARGINAL';checks.append(('negative-blind',derive(bad,p,ph)['result']=='TIER_2_ASSURED'))
 r={'status':'PASS' if all(v for _,v in checks) else 'FAIL','passed':sum(v for _,v in checks),'total':len(checks),'profile_sha256':ph,'checks':[{'name':n,'pass':v} for n,v in checks],'derived_final_result':final_result};open(z.out,'w').write(json.dumps(r,indent=2)+'\n');print(json.dumps(r,indent=2));raise SystemExit(0 if r['status']=='PASS' else 1)
main()
