package main
import("crypto/ed25519";"crypto/rand";"crypto/sha256";"encoding/base64";"encoding/hex";"encoding/json";"flag";"fmt";"os";"time")
type M=map[string]any
func mm(v any)M{return v.(map[string]any)}
func s(m M,k string)string{v,_:=m[k].(string);return v}
func f(m M,k string)float64{v,_:=m[k].(float64);return v}
func b(m M,k string)bool{v,_:=m[k].(bool);return v}
func pass(x M,p M,ph string)bool{st:=mm(x["state"]);pr:=mm(st["producer"]);c:=pr["conformance"].([]any);hb,hr:=false,false;for _,v:=range c{if v=="BS-RGU-PRODUCER-0.1"{hb=true};if v=="RGI-RGU-1.0"{hr=true}};if s(st,"spec_version")!="0.1.0"||s(st,"status")!="AVAILABLE"||!hb||!hr{return false};if s(mm(x["profile"]),"sha256")!=ph{return false};a:=mm(x["assurance"]);q:=mm(a["native_resource_quantum"]);ch:=mm(a["measurement_channel"]);me:=mm(p["measurement"]);nq:=mm(me["native_quantum"]);cp:=mm(me["channel"]);cc:=mm(ch["construction"]);vv:=mm(ch["verification"]);if s(mm(a["native_preflight"]),"status")!="PASS"||s(mm(a["adapter_fidelity"]),"status")!="PASS"||s(q,"status")!="PASS"||s(q,"unit")!=s(nq,"unit")||f(q,"quantum")>f(nq,"max_quantum")||f(q,"nonzero_probes")<f(nq,"min_nonzero_probes")||f(q,"distinct_states")<f(nq,"min_distinct_states")||s(ch,"classification")!="CHANNEL_CERTIFIED"||f(cc,"fpr")>f(cp,"fpr_max")||f(cc,"tpr")<f(cp,"tpr_min")||f(vv,"fpr")>f(cp,"fpr_max")||f(vv,"tpr")<f(cp,"tpr_min"){return false};z:=mm(x["blind"]);pc:=mm(z["prediction_commitment"]);br:=mm(z["benchmark_result"]);return s(pc,"status")=="PASS"&&b(pc,"committed_before_release")&&s(mm(z["outcome_release"]),"status")=="PASS"&&b(mm(z["outcome_release"]),"released_after_prediction")&&s(br,"status")=="PASS"&&s(pc,"predicted_class")==s(br,"observed_class")&&s(mm(x["reproducibility"]),"status")=="PASS"&&s(mm(x["canonical_finality"]),"status")=="FINAL"}
func main(){in:=flag.String("bundle","","candidate");pp:=flag.String("profile","","profile");out:=flag.String("out","final.json","out");flag.Parse();pb,_:=os.ReadFile(*pp);h:=sha256.Sum256(pb);ph:=hex.EncodeToString(h[:]);var p,x M;json.Unmarshal(pb,&p);xb,_:=os.ReadFile(*in);json.Unmarshal(xb,&x);if !pass(x,p,ph){panic("gate failure")};t:=mm(x["target"]);if s(t,"vendor_organization_id")=="vm.lab.gamma"{panic("org collision")};st:=mm(x["state"]);bp:=mm(x["profile"]);payload:=fmt.Sprintf("RGI-EVALUATOR-1.0\nbundle_id=%s\ntarget_id=%s\nstate_id=%s\nprofile_sha256=%s\nresult=TIER_3_CERTIFIED\ntier=3\n",s(x,"bundle_id"),s(t,"target_id"),s(st,"state_id"),s(bp,"sha256"));pub,priv,_:=ed25519.GenerateKey(rand.Reader);sig:=ed25519.Sign(priv,[]byte(payload));x["independent_evaluator"]=M{"evaluator_id":"vm-c-go","organization_id":"vm.lab.gamma","result":"PASS","algorithm":"Ed25519","public_key_base64":base64.StdEncoding.EncodeToString(pub),"signed_payload_base64":base64.StdEncoding.EncodeToString([]byte(payload)),"signature_base64":base64.StdEncoding.EncodeToString(sig),"evaluated_at":time.Now().UTC().Format(time.RFC3339)};x["declared_result"]=M{"tier":3.0,"result":"TIER_3_CERTIFIED","external_accreditation":false};o,_:=json.MarshalIndent(x,"","  ");os.WriteFile(*out,append(o,'\n'),0644);fmt.Printf("{\"result\":\"TIER_3_CERTIFIED\",\"tier\":3,\"profile_sha256\":\"%s\"}\n",ph)}
