import os,json,hashlib
from http.server import BaseHTTPRequestHandler,ThreadingHTTPServer
P=os.environ.get('PROFILE','vm-lab/profile.json'); pb=open(P,'rb').read(); profile=json.loads(pb); ph=hashlib.sha256(pb).hexdigest(); alpha=.61; beta=.514; theta=alpha+beta; cls='QUADRATIC'; subject='target-b-accelerator-01'
state={'spec_version':'0.1.0','state_id':'018f2e5a-8b71-7cc4-a083-d6f4cf0dd022','observed_at':'2026-08-19T12:40:00-07:00','valid_until':'2026-08-19T13:40:00-07:00','sequence':2001,'status':'AVAILABLE','producer':{'id':'rgu://vm.beta/python','implementation':'rgi-python-vm-1','version':'1.0.0','conformance':['BS-CORE-PRODUCER-0.1','BS-RGU-PRODUCER-0.1','RGI-RGU-1.0']},'subject':{'id':subject,'type':'accelerator','scope':'device'},'resources':{'primary':{'id':'bs.compute.memory.hbm.capacity','role':'PRIMARY','unit':'By','boundary':'UPPER'},'coupled':[]},'chart':{'id':'rgi.reference.hbm-saturation','version':'1','status':'CERTIFIED','source':'PROFILE_DEFINED'},'brodzinski':{'number':{'value':theta,'components':{'alpha':alpha,'beta':beta},'derivation_id':'bs.theta.alpha_plus_beta.v0.1'},'class':{'value':cls,'rule_id':'rgi.reference.class.theta-unity','rule_version':'1'}},'observability':{'status':'CERTIFIED','certificate_id':'rgi://vm/b'},'confidence':{'kind':'EMPIRICAL_RELIABILITY','value':.99,'target':'brodzinski_class','calibration_id':'vm'},'measurement':{'method_id':'bs.method.matched_state.v0.1','profile_id':'rgi.reference.hbm.matched-state.v1','decoder_fidelity':'CERTIFIED','outcome_interface':'NATIVE','evidence_ref':'sha256:'+'b'*64},'extensions':{'org.resourcegeometry.rgi':{'geometry_epoch':'vm-b-epoch-1'}}}
bundle={'schema_version':'rgi-certification-bundle/1.0','bundle_id':'vm-bundle-b','target':{'target_id':'vm-target-b','vendor_organization_id':'vm.vendor.beta','operator_organization_id':'vm.vendor.beta.operator','implementation_id':'rgi-python-vm-1'},'profile':{'profile_id':profile['profile_id'],'version':profile['version'],'sha256':ph},'state':state,'assurance':{'native_preflight':{'status':'PASS'},'adapter_fidelity':{'status':'PASS'},'native_resource_quantum':{'status':'PASS','unit':'By','quantum':67108864,'nonzero_probes':4,'distinct_states':4},'measurement_channel':{'status':'PASS','classification':'CHANNEL_CERTIFIED','construction':{'fpr':.016,'tpr':.88},'verification':{'fpr':.018,'tpr':.87}}},'blind':{'prediction_commitment':{'status':'PASS','committed_before_release':True,'predicted_class':cls},'outcome_release':{'status':'PASS','released_after_prediction':True},'benchmark_result':{'status':'PASS','observed_class':cls}},'reproducibility':{'status':'PASS'},'canonical_finality':{'status':'FINAL'},'declared_result':{'tier':2,'result':'TIER_2_ASSURED','external_accreditation':False}}
def derive(b):
 s=b['state']; p=profile['scope']; g={}; c=s['producer']['conformance']; g['protocol']=s['spec_version']=='0.1.0' and s['status']=='AVAILABLE' and 'BS-RGU-PRODUCER-0.1' in c and 'RGI-RGU-1.0' in c and abs(s['brodzinski']['number']['value']-sum(s['brodzinski']['number']['components'].values()))<1e-12; g['scope']=b['profile']['sha256']==ph and s['subject']['type']==p['subject_type'] and s['subject']['scope']==p['subject_scope'] and s['resources']['primary']['id']==p['primary_resource'] and s['chart']['id']==p['chart_id'] and s['measurement']['method_id']==p['measurement_method_id'] and s['measurement']['profile_id']==p['measurement_profile_id']
 if not all(g.values()): return {'tier':0,'result':'NONCONFORMING','gates':g}
 a=b['assurance'];q=a['native_resource_quantum'];ch=a['measurement_channel'];cp=profile['measurement']['channel'];nq=profile['measurement']['native_quantum'];g['assurance']=a['native_preflight']['status']=='PASS' and a['adapter_fidelity']['status']=='PASS' and q['status']=='PASS' and q['unit']==nq['unit'] and q['quantum']<=nq['max_quantum'] and q['nonzero_probes']>=nq['min_nonzero_probes'] and q['distinct_states']>=nq['min_distinct_states'] and ch['status']=='PASS' and ch['classification']=='CHANNEL_CERTIFIED' and ch['construction']['fpr']<=cp['fpr_max'] and ch['construction']['tpr']>=cp['tpr_min'] and ch['verification']['fpr']<=cp['fpr_max'] and ch['verification']['tpr']>=cp['tpr_min']
 if not g['assurance']: return {'tier':1,'result':'TIER_1_PROTOCOL','gates':g}
 z=b['blind'];g['final']=z['prediction_commitment']['status']=='PASS' and z['prediction_commitment']['committed_before_release'] and z['outcome_release']['status']=='PASS' and z['outcome_release']['released_after_prediction'] and z['benchmark_result']['status']=='PASS' and z['prediction_commitment']['predicted_class']==z['benchmark_result']['observed_class'] and b['reproducibility']['status']=='PASS' and b['canonical_finality']['status']=='FINAL' and bool(b.get('independent_evaluator'))
 return {'tier':3,'result':'TIER_3_CERTIFIED','gates':g} if g['final'] else {'tier':2,'result':'TIER_2_ASSURED','gates':g}
class H(BaseHTTPRequestHandler):
 def send(self,o,c=200): self.send_response(c);self.send_header('content-type','application/json');self.end_headers();self.wfile.write(json.dumps(o).encode())
 def log_message(self,*a): pass
 def do_GET(self):
  if self.path=='/rgi/v1/capabilities': return self.send({'rgi_version':'1.0.0','implementation':{'id':'rgi-python-vm-1','language':'Python'},'operator':{'organization_id':'vm.vendor.beta.operator'},'bs_core_compatibility':'BS-CORE-1.0-COMPAT','conformance_claims':['BS-RGU-PRODUCER-0.1','RGI-RGU-1.0'],'benchmark_profiles':[{'profile_id':profile['profile_id'],'version':profile['version'],'sha256':ph}],'certification_bundle_versions':['rgi-certification-bundle/1.0']})
  if '/benchmark-profiles/' in self.path:return self.send(profile)
  if '/states/' in self.path:return self.send(state)
  if '/certification-candidates/' in self.path:return self.send(bundle)
  if self.path=='/healthz':return self.send({'status':'ok'})
  self.send({'error':'NOT_FOUND'},404)
 def do_POST(self):
  if self.path!='/rgi/v1/certification/evaluate':return self.send({'error':'NOT_FOUND'},404)
  try:n=int(self.headers.get('content-length','0'));self.send(derive(json.loads(self.rfile.read(n))))
  except Exception:self.send({'error':'BAD_JSON'},400)
ThreadingHTTPServer(('127.0.0.1',int(os.environ.get('PORT','18082'))),H).serve_forever()
